spring:
  jpa:
    show_sql: true

    properties:
      hibernate:
        - dialect: org.hibernate.dialect.MySQL57Dialect
        - dialect:
            storage_engine: innodb
  h2:
    console:
      enabled: true

  # set url or it will be randomly generated
  datasource:
    url: jdbc:h2:mem:testdb

  hikari:
    jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa

  # stores session to jdbc instead of default tomcat - automatically creates table in DB
  session:
    store-type: jdbc
